name: PR check without code changes

on:
  pull_request:
    paths:
      - deployment/**
      - development/**
      - .vscode/**
      - !src/**
      - !s2i/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Skip build
      run: echo "This build has been skipped."
